CREATE DATABASE IF NOT EXISTS finpulse_db;
USE finpulse_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  focus VARCHAR(50) DEFAULT 'track',
  employment_type VARCHAR(50) DEFAULT 'salaried',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  type ENUM('expense', 'income') NOT NULL,
  amount INT NOT NULL,
  category VARCHAR(50) NOT NULL,
  note VARCHAR(255),
  is_one_off BOOLEAN DEFAULT FALSE,
  date DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS goals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  target INT NOT NULL,
  saved INT DEFAULT 0,
  deadline DATE,
  icon VARCHAR(50) DEFAULT '🎯',
  color VARCHAR(50) DEFAULT '#0A84FF',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
